### ISSUE TITLE
Error 404 after INFO - Starting Interest Rate Job - requirement failed: Minimal ERG value not met"

### ISSUE THREAD

**Issue by TheStophe** [duckpools/off-chain-bot#9]
Reporting another error from the logs, this pops up somewhat repeatably. Note this is from the Duck Pools 01 proposal bot update.

>Feb 06 20:23:39 <user> python3[3445497]: INFO - Starting Interest Rate Job
Feb 06 20:23:43 <user> python3[3445497]: {
Feb 06 20:23:43 <user> python3[3445497]:   "error" : 400,
Feb 06 20:23:43 <user> python3[3445497]:   "reason" : "bad.request",
Feb 06 20:23:43 <user> python3[3445497]:   "detail" : "Bad request List(PaymentRequest(67d7wq2KP495sNBtVThj4m7Xf2awfow9ZhdDqM6ypU5gqfwXq2tuXVem3pSgKrGNV4zwkvG6RVFcKrHN4BGfKc5Po89vtSbfsXK53RoyNaPcXiKcjNbvbVkD5EkUgLWuFsqgb9rN3bGsufABLb6rrRF4gkXLGqeYWqykuovqakoePdG5ChfeFzqPaHkBntqZ8PknmacTuJLmJ89MBdfscQf8BZzxgMco19ehR1j8rWtTQWniXYcYzpp3B1mhiReA5kURW574vNPZWBwymLMhBudfu3jDoVeFwwGaJtehDKYdT4NfA4NNyiHyRih6yNH3P5t5PKkS5cLoq8MNJucZJydjjRxzWyk2vPLtMiT43T77gfjR8Q6eWvDwBP6TUt85G362oYSvkoSXcBjbMM7KVQsK2MkAnCGtS1m3FwCn19MhdArGquoEDs9t4XBtNMwnVQsWxd4LUeAG1vakn7XiYTsmWkVbYRNJA9m95nxteWrUEvDT4ybezsdNmqUk13s8ybiR2c67iJzUCvB7zQCQQnvpWKSgtBGboDWu79reguFEXCuBm6kJddwsAniQ7Sm3poLJw8BYBCAiEBa5or7CwF5JkfYwcRdi3CoBBwoXYf3tYUJ46S8Y3X47eNbvBx29fc5tPEQ2UsU2CwdgZzFMGZUF1hfkFLwiShmGtDvxWAPuutDonrb1uWPhrPJ7E4LAVwhBkxWksfjn3BnMaZC7hRdqLjWgmgmbzQ9kKW4bco5WVwtDx42o3S1SASLMq3uhiCjiqry8E2VtRCqg2VjwXJzbrbmrQn863Rh53TwAFFTJAiqNua6zZ73,300000,List((Coll(53,-8,38,73,127,-114,-83,-11,-76,111,118,-124,-123,-50,-63,117,-61,92,17,54,11,72,33,-22,-110,-69,-66,-123,87,119,-75,92),1)),Map(R5 -> LongConstant(1194604), R8 -> TrueLeaf, R9 -> TrueLeaf, R7 -> TrueLeaf, R6 -> IntConstant(1), R4 -> ConstantNode(Coll(100000000,100000490,100000490,100004363,100003138,100000639,100001121,100001155,100003918,100003918,100003918,100003918,100001601,100001601,100001601,100001601,100000120,100000593,100000349,100000349,100000349,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100000336,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100002870,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447,100010447),Coll[SLong$]))), PaymentRequest(9gZm5sHRrTmzRaFi6VXX8rsj5V4jMMqfUMJbdskeZZz37qfEscH,610000,List(),Map()), PaymentRequest(4FC5xSYcm6fUjNGmpQJMuVW9zU4KSa9qxg2uJwEC2x2CmmdM1fUyQ7hTs8uWrqLfSNjc4j8R,1000000,List((Coll(-64,102,54,41,34,107,-23,27,48,70,6,-76,-77,-97,19,106,-64,66,35,-38,15,79,-52,-110,83,88,-91,-107,51,-9,93,100),1), (Coll(-78,126,-127,-26,-86,-14,13,-45,33,68,-4,40,-110,84,89,-55,127,-106,72,-29,84,44,-24,119,71,-128,-45,-30,-45,99,-79,-50),1)),Map()), PaymentRequest(2iHkR7CWvD1R4j1yZg5bkeDRQavjAaVPeTDFGGLZduHyfWMuYpmhHocX8GJoaieTx78FntzJbCBVL6rf96ocJoZdmWBL2fci7NqWgAirppPQmZ7fN9V6z13Ay6brPriBKYqLp1bT2Fk4FkFLCfdPpe,1290000,List(),Map())). requirement failed: Minimal ERG value not met"

**Comment by sb01101001** [comment]
Thanks for raising the issue, interest boxes were bootstrapped with low value to ensure a smooth manual transfer when switching to the parent interest reports. These transfers have worked fine and additional value was added to ERG and SigUSD pool (so they should now work automatically). For this rsADA pool, additional value has been added so the issue is now resolved.
